# _config.yml

title: OCI Kickstart Workshop
description: Oracle Cloud Infrastructure (OCI) Kickstart Workshop mit Oehrli und Berger - mit Freunden in der Cloud unterwegs
google_analytics:
source: doc
#theme: minimal-mistakes-jekyll
plugins:
  - jekyll-remote-theme

# Configure the remote_theme plugin with the gh-pages branch
# or the specific tag
remote_theme: aksakalli/jekyll-doc-theme@gh-pages   

timezone: Europe/Berlin
defaults:
- scope:
    path: lab
    type: docs
  values:
    layout: docs
    sectionid: lab

- scope:
    path: doc
    type: docs
  values:
    layout: docs
    sectionid: doc
#defaults:
#- scope:
#    path: _posts
#    type: posts
#  values:
#    layout: post
#    sectionid: blog

#- scope:
#    path: doc
#    type: docs
#  values:
#    layout: docs
#    sectionid: docs
#    seo:
#      type: "WebPage"

collections:
  docs:
    permalink: /:collection/:path/
    output: true
#  posts:
#    permalink: /blog/:year/:month/:day/:title/
#    output: true
