# _config.yml

title: OCI Kickstart Workshop
description: Oracle Cloud Infrastructure (OCI) Kickstart Workshop mit Oehrli und Berger - mit Freunden in der Cloud unterwegs
google_analytics:
source: doc
theme: jekyll-theme-architect
