# _config.yml

title: OCI Kickstart Workshop
description: Oracle Cloud Infrastructure (OCI) Kickstart Workshop mit Oehrli und Berger - mit Freunden in der Cloud unterwegs
show_downloads: true
google_analytics:
theme: jekyll-theme-architect
