# ----------------------------------------------------------------------------
# Trivadis AG, Infrastructure Managed Services
# Saegereistrasse 29, 8152 Glattbrugg, Switzerland
# ----------------------------------------------------------------------------
# Name.......: pandoc_builds.yaml 
# Author.....: Stefan Oehrli (oes) stefan.oehrli@trivadis.com
# Editor.....: Stefan Oehrli
# Date.......: 2021.02.23
# Revision...: 
# Purpose....: Pandoc build workflow to generate the different documentation
# Notes......: --
# Reference..: https://github.com/DavidAnson/markdownlint
# ----------------------------------------------------------------------------
name: Doc Build

on:
  push:
    branches: [ main ]
    paths-ignore:
      - '.github/**'

  pull_request:
    branches: [ main ]
    paths-ignore:
      - '.github/**'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  # - Check Markdown -----------------------------------------------------------
  # job to check the documentation
  check_docs:
    name: Check Markdown
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      # Check Markdown using markdownlint-cli from docker images 06kellyjac/markdownlint-cli
      - name: run markdownlint-cli
        uses: docker://06kellyjac/markdownlint-cli
        with:
          args: .

  # - Build DE docs ------------------------------------------------------------
  # Job to build the english documentation
  build_docs:
    needs: check_docs
    name: Build PDF documents
    runs-on: ubuntu-latest
    env:
      LANGUAGE: de
      DOC: doc
      LAB: lab
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Populate env variables
        run: |
          echo "MD_FILES=$(printf '%s ' ${{ env.DOC }}/[0-8]x??-*.md ${{ env.LAB }}/ex??/?x??-*.md ${{ env.DOC }}/9x??-*.md)" >> $GITHUB_ENV
          echo "REPOSITORY_NAME=$(echo '${{ github.repository }}' | awk -F '/' '{print $2}')" >> $GITHUB_ENV
      - name: simplify image resource path
        run: |
          for i in $MD_FILES ;do
            echo "process file $i"
            sed -i 's|\(./\)*../../images/|images/|' $i
          done
      # Build PDF using docker images oehrlis/pandoc
      - name: Build LAB pdf document
        uses: docker://oehrlis/pandoc
        with:
          args: >-
            --pdf-engine=xelatex 
            --listings
            --metadata-file=doc/metadata.yml
            --resource-path=.:images
            --filter pandoc-latex-environment
            --output=tvd-${{ env.REPOSITORY_NAME }}_${{ env.LANGUAGE }}.pdf ${{ env.MD_FILES }}
      
      # Build PDF using docker images oehrlis/pandoc
      - name: Build Requirements pdf document
        uses: docker://oehrlis/pandoc
        with:
          args: >-
            --pdf-engine=xelatex 
            --listings
            --metadata-file=doc/metadata_requirements.yml
            --resource-path=.:images
            --filter pandoc-latex-environment
            --output=tvd-${{ env.REPOSITORY_NAME }}_${{ env.LANGUAGE }}_requirements.pdf ${{ env.DOC }}/0x04_Requirements.md

      - name: Archive build documents
        uses: actions/upload-artifact@master
        with:
          name: Generated Documents
          path: tvd-${{ env.REPOSITORY_NAME }}*

      - name: Cache generated documents
        uses: actions/cache@v2
        env:
          cache-name: cache-documents
        with:
          # tbd
          path: tvd-${{ env.REPOSITORY_NAME }}_${{ env.LANGUAGE }}.pdf
          key: ${{ runner.os }}-build-docs-${{ hashFiles('**/tvd-*.pdf') }}
          
# - Draft release ------------------------------------------------------------
# Job to build a draft release
  pre-release:
    needs: build_docs
    name: Create draft release
    runs-on: ubuntu-latest

    steps:
      # ...
      - name: Cache generated documents
        uses: actions/cache@v2
        env:
          cache-name: cache-documents
        with:
          # tbd
          path: tvd-${{ env.REPOSITORY_NAME }}_${{ env.LANGUAGE }}.pdf
          key: ${{ runner.os }}-build-docs-${{ hashFiles('**/tvd-*.pdf') }}

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "Development Build"
          files: |
            tvd-${{ env.REPOSITORY_NAME }}*

# --- EOF -------------------------------------------------------------------
